# https://stackoverflow.com/questions/68088702/json-parse-error-on-running-hugo-command
baseURL = ""
languageCode = 'en-us'
title = "Hsun' blog"
theme = "PaperMod"


# use goldmark to render org files to markdown
[markup.goldmark.renderer]
    unsafe = true
